
// import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import AOSProvider from '@/components/AOSProvider';

const poppins = Poppins({
  subsets: [ "latin" ],
  variable: "--font-poppins",
  weight: ['400', '600', '700']
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/AFlogo2.ico" />
      </head>
      <body
        className={`${poppins.variable}`}
      >
        <AOSProvider />
        {children}
      </body>
    </html>
  );
}
